### ISSUE TITLE
Registry certificate expired error

### ISSUE THREAD

**Issue by richp10** [portainer/docker-images#9]
On RancherOS - which is succesfully installing other docker images, I run

`docker volume create portainer_data`

`docker run -d -p 8000:8000 -p 9443:9443 --name portainer --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data cr.portainer.io/portainer/portainer-ce:2.9.3`

And get error: 

`Unable to find image 'cr.portainer.io/portainer/portainer-ce:2.9.3' locally
docker: Error response from daemon: Get https://cr.portainer.io/v2/: x509: certificate has expired or is not yet valid.`

**Comment by jamescarppe** [comment]
Remove the `cr.portainer.io/` from the image reference and you should be good to go. We were using this previously for analytics on who was downloading the Portainer images but have since removed this.

Is there a reason you're using 2.9.3 when 2.11.1 is the latest version?

**Comment by richp10** [comment]
Sorry - was looking at the wrong (older) documentation. 

Folloiwng 2.11.1 docs it worked fine - thanks for the pointer..
